package com.spotify.remoteconfig;

import com.spotify.remoteconfig.zh;

public final /* synthetic */ class s3 implements o0e {
    public static final /* synthetic */ s3 a = new s3();

    private /* synthetic */ s3() {
    }

    @Override // defpackage.o0e
    public final n0e a(p0e p0e) {
        boolean a2 = p0e.a("android-music-libs-video-captions", "subtitles_autogenerated_enabled", false);
        zh.b bVar = new zh.b();
        bVar.b(false);
        bVar.b(a2);
        return bVar.a();
    }
}
