package com.spotify.remoteconfig;

import com.spotify.remoteconfig.sc;

final class zh extends sc {
    private final boolean a;

    static final class b extends sc.a {
        private Boolean a;

        b() {
        }

        public sc a() {
            String str = this.a == null ? " subtitlesAutogeneratedEnabled" : "";
            if (str.isEmpty()) {
                return new zh(this.a.booleanValue(), null);
            }
            throw new IllegalStateException(je.x0("Missing required properties:", str));
        }

        public sc.a b(boolean z) {
            this.a = Boolean.valueOf(z);
            return this;
        }
    }

    zh(boolean z, a aVar) {
        this.a = z;
    }

    @Override // com.spotify.remoteconfig.sc
    public boolean a() {
        return this.a;
    }

    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof sc) || this.a != ((sc) obj).a()) {
            return false;
        }
        return true;
    }

    public int hashCode() {
        return (this.a ? 1231 : 1237) ^ 1000003;
    }

    public String toString() {
        return je.P0(je.V0("AndroidMusicLibsVideoCaptionsProperties{subtitlesAutogeneratedEnabled="), this.a, "}");
    }
}
