package com.spotify.music.features.podcast.episode.transcript.ui.page.holders;

import android.view.View;
import com.spotify.music.features.podcast.episode.transcript.ui.page.c;
import kotlin.f;
import kotlin.jvm.internal.Lambda;
import kotlin.jvm.internal.h;

final class AutoGeneratedDisclaimerViewHolder$binder$1 extends Lambda implements rmf<c, View, f> {
    public static final AutoGeneratedDisclaimerViewHolder$binder$1 a = new AutoGeneratedDisclaimerViewHolder$binder$1();

    AutoGeneratedDisclaimerViewHolder$binder$1() {
        super(2);
    }

    /* Return type fixed from 'java.lang.Object' to match base method */
    /* JADX DEBUG: Method arguments types fixed to match base method, original types: [java.lang.Object, java.lang.Object] */
    @Override // defpackage.rmf
    public f invoke(c cVar, View view) {
        h.e(cVar, "<anonymous parameter 0>");
        h.e(view, "<anonymous parameter 1>");
        return f.a;
    }
}
