package defpackage;

import com.google.common.base.Optional;
import com.spotify.libs.search.history.h;
import com.spotify.mobile.android.hubframework.defaults.playback.HubsTracksPlayerHelper;
import com.spotify.mobile.android.hubframework.defaults.playback.i;
import com.spotify.mobile.android.rx.w;
import com.spotify.music.libs.search.transition.l;
import com.spotify.music.navigation.t;
import io.reactivex.s;
import io.reactivex.y;

/* renamed from: pf8  reason: default package */
public final class pf8 {
    private final wlf<te8> A;
    private final wlf<qd8> B;
    private final wlf<w> C;
    private final wlf<ig8> D;
    private final wlf<String> E;
    private final wlf<i5b> F;
    private final wlf<i4b> G;
    private final wlf<Boolean> H;
    private final wlf<Integer> I;
    private final wlf<i> a;
    private final wlf<HubsTracksPlayerHelper> b;
    private final wlf<x3b> c;
    private final wlf<h5b> d;
    private final wlf<ib8> e;
    private final wlf<gb8> f;
    private final wlf<fb8> g;
    private final wlf<kb8> h;
    private final wlf<t> i;
    private final wlf<yf8> j;
    private final wlf<h> k;
    private final wlf<com.spotify.libs.search.history.i> l;
    private final wlf<l> m;
    private final wlf<String> n;
    private final wlf<Boolean> o;
    private final wlf<Boolean> p;
    private final wlf<Boolean> q;
    private final wlf<Boolean> r;
    private final wlf<efa> s;
    private final wlf<s<Boolean>> t;
    private final wlf<ob8> u;
    private final wlf<s<Boolean>> v;
    private final wlf<y> w;
    private final wlf<k4b> x;
    private final wlf<io.reactivex.functions.l<Optional<b91>, Optional<b91>>> y;
    private final wlf<dd8> z;

    public pf8(wlf<i> wlf, wlf<HubsTracksPlayerHelper> wlf2, wlf<x3b> wlf3, wlf<h5b> wlf4, wlf<ib8> wlf5, wlf<gb8> wlf6, wlf<fb8> wlf7, wlf<kb8> wlf8, wlf<t> wlf9, wlf<yf8> wlf10, wlf<h> wlf11, wlf<com.spotify.libs.search.history.i> wlf12, wlf<l> wlf13, wlf<String> wlf14, wlf<Boolean> wlf15, wlf<Boolean> wlf16, wlf<Boolean> wlf17, wlf<Boolean> wlf18, wlf<efa> wlf19, wlf<s<Boolean>> wlf20, wlf<ob8> wlf21, wlf<s<Boolean>> wlf22, wlf<y> wlf23, wlf<k4b> wlf24, wlf<io.reactivex.functions.l<Optional<b91>, Optional<b91>>> wlf25, wlf<dd8> wlf26, wlf<te8> wlf27, wlf<qd8> wlf28, wlf<w> wlf29, wlf<ig8> wlf30, wlf<String> wlf31, wlf<i5b> wlf32, wlf<i4b> wlf33, wlf<Boolean> wlf34, wlf<Integer> wlf35) {
        a(wlf, 1);
        this.a = wlf;
        a(wlf2, 2);
        this.b = wlf2;
        a(wlf3, 3);
        this.c = wlf3;
        a(wlf4, 4);
        this.d = wlf4;
        a(wlf5, 5);
        this.e = wlf5;
        a(wlf6, 6);
        this.f = wlf6;
        a(wlf7, 7);
        this.g = wlf7;
        a(wlf8, 8);
        this.h = wlf8;
        a(wlf9, 9);
        this.i = wlf9;
        a(wlf10, 10);
        this.j = wlf10;
        a(wlf11, 11);
        this.k = wlf11;
        a(wlf12, 12);
        this.l = wlf12;
        a(wlf13, 13);
        this.m = wlf13;
        a(wlf14, 14);
        this.n = wlf14;
        a(wlf15, 15);
        this.o = wlf15;
        a(wlf16, 16);
        this.p = wlf16;
        a(wlf17, 17);
        this.q = wlf17;
        a(wlf18, 18);
        this.r = wlf18;
        a(wlf19, 19);
        this.s = wlf19;
        a(wlf20, 20);
        this.t = wlf20;
        a(wlf21, 21);
        this.u = wlf21;
        a(wlf22, 22);
        this.v = wlf22;
        a(wlf23, 23);
        this.w = wlf23;
        a(wlf24, 24);
        this.x = wlf24;
        a(wlf25, 25);
        this.y = wlf25;
        a(wlf26, 26);
        this.z = wlf26;
        a(wlf27, 27);
        this.A = wlf27;
        a(wlf28, 28);
        this.B = wlf28;
        a(wlf29, 29);
        this.C = wlf29;
        a(wlf30, 30);
        this.D = wlf30;
        a(wlf31, 31);
        this.E = wlf31;
        a(wlf32, 32);
        this.F = wlf32;
        a(wlf33, 33);
        this.G = wlf33;
        a(wlf34, 34);
        this.H = wlf34;
        a(wlf35, 35);
        this.I = wlf35;
    }

    private static <T> T a(T t2, int i2) {
        if (t2 != null) {
            return t2;
        }
        throw new NullPointerException(je.p0("@AutoFactory method argument is null but is not marked @Nullable. Argument index: ", i2));
    }

    public of8 b(b61 b61, wg8 wg8) {
        i iVar = this.a.get();
        a(iVar, 1);
        x3b x3b = this.c.get();
        a(x3b, 3);
        h5b h5b = this.d.get();
        a(h5b, 4);
        ib8 ib8 = this.e.get();
        a(ib8, 5);
        gb8 gb8 = this.f.get();
        a(gb8, 6);
        fb8 fb8 = this.g.get();
        a(fb8, 7);
        kb8 kb8 = this.h.get();
        a(kb8, 8);
        t tVar = this.i.get();
        a(tVar, 9);
        yf8 yf8 = this.j.get();
        a(yf8, 10);
        h hVar = this.k.get();
        a(hVar, 11);
        com.spotify.libs.search.history.i iVar2 = this.l.get();
        a(iVar2, 12);
        String str = this.n.get();
        a(str, 14);
        Boolean bool = this.o.get();
        a(bool, 15);
        boolean booleanValue = bool.booleanValue();
        Boolean bool2 = this.p.get();
        a(bool2, 16);
        boolean booleanValue2 = bool2.booleanValue();
        Boolean bool3 = this.q.get();
        a(bool3, 17);
        boolean booleanValue3 = bool3.booleanValue();
        Boolean bool4 = this.r.get();
        a(bool4, 18);
        boolean booleanValue4 = bool4.booleanValue();
        efa efa = this.s.get();
        a(efa, 19);
        efa efa2 = efa;
        s<Boolean> sVar = this.t.get();
        a(sVar, 20);
        s<Boolean> sVar2 = sVar;
        ob8 ob8 = this.u.get();
        a(ob8, 21);
        ob8 ob82 = ob8;
        s<Boolean> sVar3 = this.v.get();
        a(sVar3, 22);
        s<Boolean> sVar4 = sVar3;
        y yVar = this.w.get();
        a(yVar, 23);
        y yVar2 = yVar;
        k4b k4b = this.x.get();
        a(k4b, 24);
        k4b k4b2 = k4b;
        io.reactivex.functions.l<Optional<b91>, Optional<b91>> lVar = this.y.get();
        a(lVar, 25);
        io.reactivex.functions.l<Optional<b91>, Optional<b91>> lVar2 = lVar;
        dd8 dd8 = this.z.get();
        a(dd8, 26);
        dd8 dd82 = dd8;
        te8 te8 = this.A.get();
        a(te8, 27);
        te8 te82 = te8;
        qd8 qd8 = this.B.get();
        a(qd8, 28);
        qd8 qd82 = qd8;
        w wVar = this.C.get();
        a(wVar, 29);
        w wVar2 = wVar;
        ig8 ig8 = this.D.get();
        a(ig8, 30);
        ig8 ig82 = ig8;
        String str2 = this.E.get();
        a(str2, 31);
        String str3 = str2;
        i5b i5b = this.F.get();
        a(i5b, 32);
        i5b i5b2 = i5b;
        i4b i4b = this.G.get();
        a(i4b, 33);
        i4b i4b2 = i4b;
        Boolean bool5 = this.H.get();
        a(bool5, 34);
        boolean booleanValue5 = bool5.booleanValue();
        Integer num = this.I.get();
        a(num, 35);
        int intValue = num.intValue();
        a(b61, 36);
        a(wg8, 37);
        return new of8(iVar, this.b.get(), x3b, h5b, ib8, gb8, fb8, kb8, tVar, yf8, hVar, iVar2, this.m.get(), str, booleanValue, booleanValue2, booleanValue3, booleanValue4, efa2, sVar2, ob82, sVar4, yVar2, k4b2, lVar2, dd82, te82, qd82, wVar2, ig82, str3, i5b2, i4b2, booleanValue5, intValue, b61, wg8);
    }
}
