package com.spotify.music.features.settings.adapter;

import android.content.Context;
import android.content.res.Resources;
import com.google.protobuf.u;
import com.spotify.android.flags.c;
import com.spotify.encore.mobile.snackbar.SnackbarManager;
import com.spotify.mobile.android.util.prefs.SpSharedPreferences;
import com.spotify.mobile.android.util.prefs.i;
import com.spotify.mobile.android.util.t;
import com.spotify.music.features.localfilesimport.util.b;
import com.spotify.music.features.settings.x0;
import com.spotify.music.libs.carmodeengine.util.y;
import com.spotify.music.libs.voice.e;
import com.spotify.music.premiummini.k;
import com.spotify.music.samsungpersonalization.SamsungPersonalizationSettingsHandler;
import com.spotify.music.settings.a;
import com.spotify.music.z0;
import com.spotify.remoteconfig.AppsMusicLibsRemoteconfigProperties;
import com.spotify.remoteconfig.cj;
import com.spotify.remoteconfig.pj;
import com.spotify.ubi.specification.factories.r3;
import defpackage.ov9;
import defpackage.sba;
import java.util.Random;

public final class t2 implements fjf<p2> {
    private final wlf<or9> A;
    private final wlf<i> B;
    private final wlf<mk8> C;
    private final wlf<Boolean> D;
    private final wlf<Boolean> E;
    private final wlf<cif> F;
    private final wlf<e> G;
    private final wlf<Boolean> H;
    private final wlf<er0> I;
    private final wlf<lr0> J;
    private final wlf<sba.a> K;
    private final wlf<wj8> L;
    private final wlf<nk8> M;
    private final wlf<ok8> N;
    private final wlf<com.spotify.music.email.e> O;
    private final wlf<com.spotify.music.features.ads.cmp.i> P;
    private final wlf<k> Q;
    private final wlf<z0> R;
    private final wlf<String> S;
    private final wlf<String> T;
    private final wlf<SnackbarManager> U;
    private final wlf<pj> V;
    private final wlf<cj> W;
    private final wlf<lr9> X;
    private final wlf<b> Y;
    private final wlf<SamsungPersonalizationSettingsHandler> Z;
    private final wlf<Context> a;
    private final wlf<ov9.a> a0;
    private final wlf<Resources> b;
    private final wlf<String> b0;
    private final wlf<c> c;
    private final wlf<Boolean> c0;
    private final wlf<t> d;
    private final wlf<Random> d0;
    private final wlf<cqe> e;
    private final wlf<Boolean> e0;
    private final wlf<fm9> f;
    private final wlf<uda> g;
    private final wlf<com.spotify.music.features.datasavermode.settings.e> h;
    private final wlf<kz1> i;
    private final wlf<SpSharedPreferences<Object>> j;
    private final wlf<AppsMusicLibsRemoteconfigProperties> k;
    private final wlf<dca> l;
    private final wlf<com.spotify.credentials.store.b> m;
    private final wlf<com.spotify.music.inappmessaging.b> n;
    private final wlf<sv3> o;
    private final wlf<a> p;
    private final wlf<dd0> q;
    private final wlf<gl0<u>> r;
    private final wlf<mba> s;
    private final wlf<m52> t;
    private final wlf<x0> u;
    private final wlf<ere> v;
    private final wlf<r3> w;
    private final wlf<nl2> x;
    private final wlf<m41> y;
    private final wlf<y> z;

    public t2(wlf<Context> wlf, wlf<Resources> wlf2, wlf<c> wlf3, wlf<t> wlf4, wlf<cqe> wlf5, wlf<fm9> wlf6, wlf<uda> wlf7, wlf<com.spotify.music.features.datasavermode.settings.e> wlf8, wlf<kz1> wlf9, wlf<SpSharedPreferences<Object>> wlf10, wlf<AppsMusicLibsRemoteconfigProperties> wlf11, wlf<dca> wlf12, wlf<com.spotify.credentials.store.b> wlf13, wlf<com.spotify.music.inappmessaging.b> wlf14, wlf<sv3> wlf15, wlf<a> wlf16, wlf<dd0> wlf17, wlf<gl0<u>> wlf18, wlf<mba> wlf19, wlf<m52> wlf20, wlf<x0> wlf21, wlf<ere> wlf22, wlf<r3> wlf23, wlf<nl2> wlf24, wlf<m41> wlf25, wlf<y> wlf26, wlf<or9> wlf27, wlf<i> wlf28, wlf<mk8> wlf29, wlf<Boolean> wlf30, wlf<Boolean> wlf31, wlf<cif> wlf32, wlf<e> wlf33, wlf<Boolean> wlf34, wlf<er0> wlf35, wlf<lr0> wlf36, wlf<sba.a> wlf37, wlf<wj8> wlf38, wlf<nk8> wlf39, wlf<ok8> wlf40, wlf<com.spotify.music.email.e> wlf41, wlf<com.spotify.music.features.ads.cmp.i> wlf42, wlf<k> wlf43, wlf<z0> wlf44, wlf<String> wlf45, wlf<String> wlf46, wlf<SnackbarManager> wlf47, wlf<pj> wlf48, wlf<cj> wlf49, wlf<lr9> wlf50, wlf<b> wlf51, wlf<SamsungPersonalizationSettingsHandler> wlf52, wlf<ov9.a> wlf53, wlf<String> wlf54, wlf<Boolean> wlf55, wlf<Random> wlf56, wlf<Boolean> wlf57) {
        this.a = wlf;
        this.b = wlf2;
        this.c = wlf3;
        this.d = wlf4;
        this.e = wlf5;
        this.f = wlf6;
        this.g = wlf7;
        this.h = wlf8;
        this.i = wlf9;
        this.j = wlf10;
        this.k = wlf11;
        this.l = wlf12;
        this.m = wlf13;
        this.n = wlf14;
        this.o = wlf15;
        this.p = wlf16;
        this.q = wlf17;
        this.r = wlf18;
        this.s = wlf19;
        this.t = wlf20;
        this.u = wlf21;
        this.v = wlf22;
        this.w = wlf23;
        this.x = wlf24;
        this.y = wlf25;
        this.z = wlf26;
        this.A = wlf27;
        this.B = wlf28;
        this.C = wlf29;
        this.D = wlf30;
        this.E = wlf31;
        this.F = wlf32;
        this.G = wlf33;
        this.H = wlf34;
        this.I = wlf35;
        this.J = wlf36;
        this.K = wlf37;
        this.L = wlf38;
        this.M = wlf39;
        this.N = wlf40;
        this.O = wlf41;
        this.P = wlf42;
        this.Q = wlf43;
        this.R = wlf44;
        this.S = wlf45;
        this.T = wlf46;
        this.U = wlf47;
        this.V = wlf48;
        this.W = wlf49;
        this.X = wlf50;
        this.Y = wlf51;
        this.Z = wlf52;
        this.a0 = wlf53;
        this.b0 = wlf54;
        this.c0 = wlf55;
        this.d0 = wlf56;
        this.e0 = wlf57;
    }

    @Override // defpackage.wlf
    public Object get() {
        return new p2(this.a.get(), this.b.get(), this.c.get(), this.d.get(), this.e.get(), this.f.get(), this.g.get(), this.h.get(), this.i.get(), this.j.get(), this.k.get(), this.l.get(), this.m.get(), this.n.get(), this.o.get(), this.p.get(), this.q.get(), this.r.get(), this.s.get(), this.t.get(), this.u.get(), this.v.get(), this.w.get(), this.x.get(), this.y.get(), this.z.get(), this.A.get(), this.B.get(), this.C.get(), this.D.get().booleanValue(), this.E.get().booleanValue(), this.F.get(), this.G.get(), this.H.get().booleanValue(), this.I.get(), this.J.get(), this.K.get(), this.L.get(), this.M.get(), this.N.get(), this.O.get(), this.P.get(), this.Q.get(), this.R.get(), this.S.get(), this.T.get(), this.U.get(), this.V.get(), this.W.get(), this.X.get(), this.Y.get(), this.Z.get(), this.a0.get(), this.b0.get(), this.c0.get().booleanValue(), this.d0.get(), this.e0.get().booleanValue());
    }
}
