package com.spotify.mobile.android.ui.contextmenu;

import android.app.Activity;
import com.spotify.android.glue.patterns.contextmenu.model.ContextMenuViewModel;
import com.spotify.encore.mobile.snackbar.SnackbarManager;
import com.spotify.music.features.addtoplaylist.d;
import com.spotify.music.features.editplaylist.g;
import com.spotify.music.follow.m;
import com.spotify.music.libs.viewuri.c;
import com.spotify.music.libs.yourlibraryx.pin.a;
import com.spotify.music.playlist.service.b;
import com.spotify.music.sleeptimer.n;
import com.spotify.music.spotlets.offline.util.e;
import com.spotify.music.z0;
import defpackage.ij9;
import defpackage.t8a;

public final class o3 implements u3 {
    private final wlf<b.a> A;
    private final wlf<a> B;
    private final wlf<r9b> a;
    private final wlf<g22> b;
    private final wlf<SnackbarManager> c;
    private final wlf<jz1> d;
    private final wlf<fm9> e;
    private final wlf<m> f;
    private final wlf<n> g;
    private final wlf<cqe> h;
    private final wlf<nsb> i;
    private final wlf<vka> j;
    private final wlf<Activity> k;
    private final wlf<com.spotify.music.navigation.b> l;
    private final wlf<d> m;
    private final wlf<g> n;
    private final wlf<com.spotify.music.features.renameplaylist.d> o;
    private final wlf<xec> p;
    private final wlf<vxc> q;
    private final wlf<t8b> r;
    private final wlf<ajf<caa>> s;
    private final wlf<kzc> t;
    private final wlf<e> u;
    private final wlf<t8a.a> v;
    private final wlf<ih0> w;
    private final wlf<ere> x;
    private final wlf<bre> y;
    private final wlf<z0> z;

    public o3(wlf<r9b> wlf, wlf<g22> wlf2, wlf<SnackbarManager> wlf3, wlf<jz1> wlf4, wlf<fm9> wlf5, wlf<m> wlf6, wlf<n> wlf7, wlf<cqe> wlf8, wlf<nsb> wlf9, wlf<vka> wlf10, wlf<Activity> wlf11, wlf<com.spotify.music.navigation.b> wlf12, wlf<d> wlf13, wlf<g> wlf14, wlf<com.spotify.music.features.renameplaylist.d> wlf15, wlf<xec> wlf16, wlf<vxc> wlf17, wlf<t8b> wlf18, wlf<ajf<caa>> wlf19, wlf<kzc> wlf20, wlf<e> wlf21, wlf<t8a.a> wlf22, wlf<ih0> wlf23, wlf<ere> wlf24, wlf<bre> wlf25, wlf<z0> wlf26, wlf<b.a> wlf27, wlf<a> wlf28) {
        b(wlf, 1);
        this.a = wlf;
        b(wlf2, 2);
        this.b = wlf2;
        b(wlf3, 3);
        this.c = wlf3;
        b(wlf4, 4);
        this.d = wlf4;
        b(wlf5, 5);
        this.e = wlf5;
        b(wlf6, 6);
        this.f = wlf6;
        b(wlf7, 7);
        this.g = wlf7;
        b(wlf8, 8);
        this.h = wlf8;
        b(wlf9, 9);
        this.i = wlf9;
        b(wlf10, 10);
        this.j = wlf10;
        b(wlf11, 11);
        this.k = wlf11;
        b(wlf12, 12);
        this.l = wlf12;
        b(wlf13, 13);
        this.m = wlf13;
        b(wlf14, 14);
        this.n = wlf14;
        b(wlf15, 15);
        this.o = wlf15;
        b(wlf16, 16);
        this.p = wlf16;
        b(wlf17, 17);
        this.q = wlf17;
        b(wlf18, 18);
        this.r = wlf18;
        b(wlf19, 19);
        this.s = wlf19;
        b(wlf20, 20);
        this.t = wlf20;
        b(wlf21, 21);
        this.u = wlf21;
        b(wlf22, 22);
        this.v = wlf22;
        b(wlf23, 23);
        this.w = wlf23;
        b(wlf24, 24);
        this.x = wlf24;
        b(wlf25, 25);
        this.y = wlf25;
        b(wlf26, 26);
        this.z = wlf26;
        b(wlf27, 27);
        this.A = wlf27;
        b(wlf28, 28);
        this.B = wlf28;
    }

    private static <T> T b(T t2, int i2) {
        if (t2 != null) {
            return t2;
        }
        throw new NullPointerException(je.p0("@AutoFactory method argument is null but is not marked @Nullable. Argument index: ", i2));
    }

    @Override // com.spotify.mobile.android.ui.contextmenu.u3
    public ContextMenuHelper a(ifd ifd, ij9.b bVar, c cVar, ContextMenuViewModel contextMenuViewModel, s3 s3Var, com.spotify.android.flags.c cVar2) {
        r9b r9b = this.a.get();
        b(r9b, 1);
        g22 g22 = this.b.get();
        b(g22, 2);
        SnackbarManager snackbarManager = this.c.get();
        b(snackbarManager, 3);
        jz1 jz1 = this.d.get();
        b(jz1, 4);
        fm9 fm9 = this.e.get();
        b(fm9, 5);
        m mVar = this.f.get();
        b(mVar, 6);
        n nVar = this.g.get();
        b(nVar, 7);
        cqe cqe = this.h.get();
        b(cqe, 8);
        nsb nsb = this.i.get();
        b(nsb, 9);
        vka vka = this.j.get();
        b(vka, 10);
        Activity activity = this.k.get();
        b(activity, 11);
        com.spotify.music.navigation.b bVar2 = this.l.get();
        b(bVar2, 12);
        d dVar = this.m.get();
        b(dVar, 13);
        g gVar = this.n.get();
        b(gVar, 14);
        com.spotify.music.features.renameplaylist.d dVar2 = this.o.get();
        b(dVar2, 15);
        com.spotify.music.features.renameplaylist.d dVar3 = dVar2;
        xec xec = this.p.get();
        b(xec, 16);
        xec xec2 = xec;
        vxc vxc = this.q.get();
        b(vxc, 17);
        vxc vxc2 = vxc;
        t8b t8b = this.r.get();
        b(t8b, 18);
        t8b t8b2 = t8b;
        ajf<caa> ajf = this.s.get();
        b(ajf, 19);
        ajf<caa> ajf2 = ajf;
        kzc kzc = this.t.get();
        b(kzc, 20);
        kzc kzc2 = kzc;
        e eVar = this.u.get();
        b(eVar, 21);
        e eVar2 = eVar;
        t8a.a aVar = this.v.get();
        b(aVar, 22);
        t8a.a aVar2 = aVar;
        ih0 ih0 = this.w.get();
        b(ih0, 23);
        ih0 ih02 = ih0;
        ere ere = this.x.get();
        b(ere, 24);
        ere ere2 = ere;
        bre bre = this.y.get();
        b(bre, 25);
        bre bre2 = bre;
        b(ifd, 26);
        b(bVar, 27);
        b(cVar, 28);
        z0 z0Var = this.z.get();
        b(z0Var, 29);
        z0 z0Var2 = z0Var;
        b.a aVar3 = this.A.get();
        b(aVar3, 30);
        b.a aVar4 = aVar3;
        b(contextMenuViewModel, 31);
        b(s3Var, 32);
        b(cVar2, 33);
        a aVar5 = this.B.get();
        b(aVar5, 34);
        return new ContextMenuHelper(r9b, g22, snackbarManager, jz1, fm9, mVar, nVar, cqe, nsb, vka, activity, bVar2, dVar, gVar, dVar3, xec2, vxc2, t8b2, ajf2, kzc2, eVar2, aVar2, ih02, ere2, bre2, ifd, bVar, cVar, z0Var2, aVar4, contextMenuViewModel, s3Var, cVar2, aVar5);
    }
}
