package com.spotify.music.features.premiumdestination;

import android.content.Context;
import com.spotify.mobile.android.hubframework.defaults.v;
import com.spotify.music.C0707R;
import com.spotify.music.features.premiumdestination.view.b0;
import com.spotify.music.features.premiumdestination.view.d0;
import com.spotify.music.features.premiumdestination.view.f0;
import com.spotify.music.features.premiumdestination.view.h0;
import com.spotify.music.features.premiumdestination.view.j;
import com.spotify.music.features.premiumdestination.view.j0;
import com.spotify.music.features.premiumdestination.view.l;
import com.spotify.music.features.premiumdestination.view.l0;
import com.spotify.music.features.premiumdestination.view.n;
import com.spotify.music.features.premiumdestination.view.n0;
import com.spotify.music.features.premiumdestination.view.p;
import com.spotify.music.features.premiumdestination.view.p0;
import com.spotify.music.features.premiumdestination.view.r;
import com.spotify.music.features.premiumdestination.view.r0;
import com.spotify.music.features.premiumdestination.view.t;
import com.spotify.music.features.premiumdestination.view.t0;
import com.spotify.music.features.premiumdestination.view.v0;
import com.spotify.music.features.premiumdestination.view.x0;
import com.spotify.music.features.premiumdestination.view.z;
import com.spotify.music.libs.viewuri.c;
import defpackage.w51;
import java.util.Map;

public final class x implements fjf<w51> {
    private final wlf<dj7> A;
    private final wlf<kj7> B;
    private final wlf<v> a;
    private final wlf<Context> b;
    private final wlf<c.a> c;
    private final wlf<Map<String, a71>> d;
    private final wlf<com.spotify.music.features.premiumdestination.view.x> e;
    private final wlf<z> f;
    private final wlf<t0> g;
    private final wlf<v0> h;
    private final wlf<x0> i;
    private final wlf<r0> j;
    private final wlf<j> k;
    private final wlf<d0> l;
    private final wlf<n0> m;
    private final wlf<l0> n;
    private final wlf<h0> o;
    private final wlf<f0> p;
    private final wlf<j0> q;
    private final wlf<l> r;
    private final wlf<b0> s;
    private final wlf<n> t;
    private final wlf<p> u;
    private final wlf<r> v;
    private final wlf<t> w;
    private final wlf<com.spotify.music.features.premiumdestination.view.v> x;
    private final wlf<p0> y;
    private final wlf<gj7> z;

    public x(wlf<v> wlf, wlf<Context> wlf2, wlf<c.a> wlf3, wlf<Map<String, a71>> wlf4, wlf<com.spotify.music.features.premiumdestination.view.x> wlf5, wlf<z> wlf6, wlf<t0> wlf7, wlf<v0> wlf8, wlf<x0> wlf9, wlf<r0> wlf10, wlf<j> wlf11, wlf<d0> wlf12, wlf<n0> wlf13, wlf<l0> wlf14, wlf<h0> wlf15, wlf<f0> wlf16, wlf<j0> wlf17, wlf<l> wlf18, wlf<b0> wlf19, wlf<n> wlf20, wlf<p> wlf21, wlf<r> wlf22, wlf<t> wlf23, wlf<com.spotify.music.features.premiumdestination.view.v> wlf24, wlf<p0> wlf25, wlf<gj7> wlf26, wlf<dj7> wlf27, wlf<kj7> wlf28) {
        this.a = wlf;
        this.b = wlf2;
        this.c = wlf3;
        this.d = wlf4;
        this.e = wlf5;
        this.f = wlf6;
        this.g = wlf7;
        this.h = wlf8;
        this.i = wlf9;
        this.j = wlf10;
        this.k = wlf11;
        this.l = wlf12;
        this.m = wlf13;
        this.n = wlf14;
        this.o = wlf15;
        this.p = wlf16;
        this.q = wlf17;
        this.r = wlf18;
        this.s = wlf19;
        this.t = wlf20;
        this.u = wlf21;
        this.v = wlf22;
        this.w = wlf23;
        this.x = wlf24;
        this.y = wlf25;
        this.z = wlf26;
        this.A = wlf27;
        this.B = wlf28;
    }

    @Override // defpackage.wlf
    public Object get() {
        com.spotify.music.features.premiumdestination.view.x xVar = this.e.get();
        z zVar = this.f.get();
        t0 t0Var = this.g.get();
        v0 v0Var = this.h.get();
        x0 x0Var = this.i.get();
        r0 r0Var = this.j.get();
        j jVar = this.k.get();
        d0 d0Var = this.l.get();
        n0 n0Var = this.m.get();
        l0 l0Var = this.n.get();
        h0 h0Var = this.o.get();
        f0 f0Var = this.p.get();
        j0 j0Var = this.q.get();
        l lVar = this.r.get();
        b0 b0Var = this.s.get();
        n nVar = this.t.get();
        p pVar = this.u.get();
        r rVar = this.v.get();
        t tVar = this.w.get();
        com.spotify.music.features.premiumdestination.view.v vVar = this.x.get();
        p0 p0Var = this.y.get();
        gj7 gj7 = this.z.get();
        dj7 dj7 = this.A.get();
        kj7 kj7 = this.B.get();
        w51.b b2 = this.a.get().a(this.b.get(), this.c.get()).a(this.d.get()).b();
        xVar.getClass();
        b2.j(C0707R.id.hubs_premium_page_gradient, "premiumPage:gradient", xVar);
        zVar.getClass();
        b2.j(C0707R.id.hubs_premium_page_header, "premiumPage:header", zVar);
        t0Var.getClass();
        b2.j(C0707R.id.hubs_premium_page_value_card_free, "premiumPage:valueCardFree", t0Var);
        v0Var.getClass();
        b2.j(C0707R.id.hubs_premium_page_value_card_premium, "premiumPage:valueCardPremium", v0Var);
        x0Var.getClass();
        b2.j(C0707R.id.hubs_premium_page_value_card_single, "premiumPage:valueCardSingle", x0Var);
        r0Var.getClass();
        b2.j(C0707R.id.hubs_premium_page_value_card, "premiumPage:valueCard", r0Var);
        jVar.getClass();
        b2.j(C0707R.id.hubs_premium_page_carousel, "premiumPage:carousel", jVar);
        d0Var.getClass();
        b2.j(C0707R.id.hubs_premium_page_offer_card, "premiumPage:offerCard", d0Var);
        n0Var.getClass();
        b2.j(C0707R.id.hubs_premium_page_offer_title_price_period, "premiumPage:offerTitlePricePeriod", n0Var);
        l0Var.getClass();
        b2.j(C0707R.id.hubs_premium_page_offer_title, "premiumPage:offerTitle", l0Var);
        h0Var.getClass();
        b2.j(C0707R.id.hubs_premium_page_offer_description, "premiumPage:offerDescription", h0Var);
        f0Var.getClass();
        b2.j(C0707R.id.hubs_premium_page_offer_cta, "premiumPage:offerCta", f0Var);
        j0Var.getClass();
        b2.j(C0707R.id.hubs_premium_page_offer_legal_text, "premiumPage:offerLegalText", j0Var);
        lVar.getClass();
        b2.j(C0707R.id.hubs_premium_page_current_plan_card, "premiumPage:currentPlanCard", lVar);
        b0Var.getClass();
        b2.j(C0707R.id.hubs_premium_page_image, "premiumPage:image", b0Var);
        nVar.getClass();
        b2.j(C0707R.id.hubs_premium_page_flexbox_button, "premiumPage:flexboxButton", nVar);
        pVar.getClass();
        b2.j(C0707R.id.hubs_premium_page_flexbox_container, "premiumPage:flexboxContainer", pVar);
        rVar.getClass();
        b2.j(C0707R.id.hubs_premium_page_flexbox_legal, "premiumPage:flexboxLegal", rVar);
        tVar.getClass();
        b2.j(C0707R.id.hubs_premium_page_flexbox_subtitle, "premiumPage:flexboxSubtitle", tVar);
        vVar.getClass();
        b2.j(C0707R.id.hubs_premium_page_flexbox_title, "premiumPage:flexboxTitle", vVar);
        p0Var.getClass();
        b2.j(C0707R.id.hubs_premium_page_section_header, "premiumPage:sectionHeader", p0Var);
        gj7.getClass();
        b2.j(C0707R.id.hubs_premium_page_benefit_list, "premiumPage:benefitList", gj7);
        dj7.getClass();
        b2.j(C0707R.id.hubs_premium_page_benefit_chart, "premiumPage:benefitChart", dj7);
        kj7.getClass();
        b2.j(C0707R.id.header_full_bleed, "premiumPage:visualHeader", kj7);
        return b2.a();
    }
}
